### ISSUE TITLE
terraform s3 error on CIrcleCI- aws.Config.CredentialsChainVerboseErrors terraform

### ISSUE THREAD

**Issue by ashraf-minhaj** [hashicorp/learn-terraform-circleci#31]
I am using AWS docker image on circleci pipeline.
```
  init-tf:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: list of things in that
          command: ls -a
      - run:
          name: terraform init
          command: sh scripts/init.sh dev
```
When I apply this error message pops up.
```
Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

And this is my backend tf file with backend -
```
provider "aws" {
	access_key = "${var.aws_access_key}"
    secret_key = "${var.aws_secret_key}"
    region  = "${var.aws_region}"
}

terraform {
  backend "s3" {

  }
}
```
I have added my access_key credentials in `environment variable` but it keeps throwing this error.
Someone on stackoverflow suggested to hard code credentials on tf code or pass while init, but it should not be a good practice and threat for public projects.
Please note that the same codes and commands work on my unix machine (mac air m1).

Any idea how I can solve this for circleci?
